"""Scaffold sanity tests: package import, smoke scripts compile, .env.example has no secrets."""

import py_compile
from pathlib import Path

import doorstep_agent

ROOT = Path(__file__).resolve().parents[1]

SECRET_KEYS = {
    "TWILIO_SUBACCOUNT_SID",
    "TWILIO_SUBACCOUNT_TOKEN",
    "TELEGRAM_BOT_TOKEN",
    "CAPTAIN_PASSCODE",
    "INTERNAL_HMAC_SECRET",
    "ORIGIN_SECRET_HEADER",
}


def test_package_has_version() -> None:
    assert doorstep_agent.__version__


def test_package_docstring_names_strands_agents() -> None:
    assert "Strands Agents" in (doorstep_agent.__doc__ or "")


def test_smoke_scripts_compile() -> None:
    scripts = [
        p
        for p in (ROOT / "scripts" / "smoke").rglob("*.py")
        if "DoorstepHello" not in p.parts  # generated by `agentcore create`, not ours
    ]
    assert scripts, "no smoke scripts found"
    for script in scripts:
        py_compile.compile(str(script), doraise=True)


def _parse_env_example() -> dict[str, str]:
    values: dict[str, str] = {}
    for raw in (ROOT / ".env.example").read_text().splitlines():
        line = raw.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, value = line.split("=", 1)
        values[key.strip()] = value.strip()
    return values


def test_env_example_lists_every_secret_blank() -> None:
    values = _parse_env_example()
    for key in SECRET_KEYS:
        assert key in values, f"{key} missing from .env.example"
        assert values[key] == "", f"{key} must be blank in .env.example"


def test_env_example_model_ids_match_verified_ids() -> None:
    values = _parse_env_example()
    assert values["DOORSTEP_MODEL_AGENT"] == "us.amazon.nova-2-lite-v1:0"
    assert values["DOORSTEP_MODEL_VOICE"] == "amazon.nova-2-sonic-v1:0"
